name: Expo Build APK
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Install dependencies
        run: npm install

      - name: Build APK en Ligne
        env:
          EXPO_TOKEN: "hhyJupdt76HX9va1sL2HAQGSA_NBhp4D8T0Q6dtF"
        run: |
          eas project:init --force
          eas build --platform android --profile preview --non-interactive --auto-credentials
