name: Expo Build APK
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Install dependencies
        run: npm install

      - name: Build APK en Ligne
        env:
          EXPO_TOKEN: "hhyJupdt76HX9va1sL2HAQGSA_NBhp4D8T0Q6dtF"
          EAS_NO_VCS: "1"
        run: |
          eas project:init --force
          # Mamorona Keystore tsotra ho an'ny Android eo an-toerana mba tsy hangatahan'ny Expo fanontaniana
          keytool -genkey -v -keystore release-key.keystore -alias my-key-alias -keyalg RSA -keysize 2048 -validity 10000 -storepass "diasofiditray" -keypass "diasofiditray" -dname "CN=AMM, OU=AMM, O=AMM, L=Arivonimamo, S=Analamanga, C=MG"
          
          # Tenenina ny Expo mba hampiasa an'io Keystore vao namboarina io
          export APP_ENV_ANDROID_KEYSTORE_PATH="release-key.keystore"
          export APP_ENV_ANDROID_KEYSTORE_PASSWORD="diasofiditray"
          export APP_ENV_ANDROID_KEY_ALIAS="my-key-alias"
          export APP_ENV_ANDROID_KEY_PASSWORD="diasofiditray"
          
          # Mandefa ny build amin'izay
          eas build --platform android --profile preview --non-interactive
