name: Expo Build APK
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Install dependencies
        run: npm install

      - name: Build APK en Ligne
        env:
          EXPO_TOKEN: "hhyJupdt76HX9va1sL2HAQGSA_NBhp4D8T0Q6dtF"
          EAS_NO_VCS: "1"
        run: |
          eas project:init --force
          
          # 1. Mamorona Keystore eo an-toerana
          keytool -genkey -v -keystore release-key.keystore -alias my-key-alias -keyalg RSA -keysize 2048 -validity 10000 -storepass "diasofiditray" -keypass "diasofiditray" -dname "CN=AMM, OU=AMM, O=AMM, L=Arivonimamo, S=Analamanga, C=MG"
          
          # 2. Mamorona credentials.json ho an'ny EAS
          echo '{
            "android": {
              "keystore": {
                "keystorePath": "release-key.keystore",
                "keystorePassword": "diasofiditray",
                "keyAlias": "my-key-alias",
                "keyPassword": "diasofiditray"
              }
            }
          }' > credentials.json
          
          # 3. Manao prebuild eo an-toerana mba hahitana izay diso rehetra alohan'ny EAS
          npx expo prebuild --clean --platform android
          
          # 4. Mandefa ny build mivantana any amin'ny Expo
          eas build --platform android --profile preview --non-interactive
